/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javalang.basics.app;

import static javalang.basics.app.MessageUtils.getMessage;
import static javalang.basics.utilities.StringUtils.join;
import static javalang.basics.utilities.StringUtils.split;

import org.apache.commons.text.WordUtils;

import javalang.basics.list.LinkedList;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
